<?php 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require("PHPMailer-master/src/PHPMailer.php");
require("PHPMailer-master/src/SMTP.php");
require("PHPMailer-master/src/Exception.php");


$email = $_POST['email'];
$fn = $_POST['fn'];
$message = $_POST['message'];
$products = $_POST['products'];
$bodyContent = "<b>Selected Product:</b> <br>".$products."<br>"."<b>Message :</b> <br>".$message;
//echo $bodyContent;exit;
if($email != ''){
	$response_array['email'] = $email;
	
	$mail = new \PHPMailer\PHPMailer\PHPMailer();
	//$mail->isSMTP();
	$mail->Host = "smtp.gmail.com";
	$mail->SMTPAuth = true;
	$mail->Username = "Kumaraa.well@gmail.com"; //paste one generated by Mailtrap
	$mail->Password = "Vel@2020@Bha#"; //paste one generated by Mailtrap
	$mail->SMTPSecure = 'tls';
	$mail->Port = 587;

	$address = "kumaraa.well@gmail.com";

	$mail->setFrom($address, 'BHN Contact Form Submission');
	$mail->addAddress($email, $fn);
	$mail->isHTML(true);

	$mail->Subject = "BHN Contact Form Submission";
	$mail->Body = $bodyContent;

	if(!$mail->send()){
	echo "Message could not be sent.";
	echo json_encode(array('flag'=>'mailer-error',"message"=>'Try Again Later'));
	}else{
	echo json_encode(array('flag'=>'success',"message"=>'Mail sent successfully'));
	exit;
	}
}
	
?>