<?php 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require("PHPMailer-master/src/PHPMailer.php");
require("PHPMailer-master/src/SMTP.php");
require("PHPMailer-master/src/Exception.php");


$email = $_POST['email'];
$phone = $_POST['phone'];
$fn = $_POST['fn'];
$ln = $_POST['ln'];
$org_name = $_POST['org_name'];
$cname = $_POST['cname'];
$message = $_POST['message'];
$products = $_POST['products'];
if (isset($cname)) {
	$bodyContent = "<b>Contact Person:</b> ".$cname."<br><b>ORGANISATION NAME:</b> ".$org_name."<br><b>Selected Product:</b> ".$products."<br>"."<b>Message :</b> ".$message." <br><b>Mobile Number:</b> ".$phone." <br> <b>Email:</b> ".$email;
}else{
	$bodyContent = "<b>First Name:</b> ".$fn."<br><b>Last Name:</b> ".$ln."<br><b>Selected Product:</b> ".$products."<br>"."<b>Message :</b> ".$message." <br><b>Mobile Number:</b> ".$phone." <br> <b>Email:</b> ".$email;
}

//echo $bodyContent;exit;
if($email != ''){
	$response_array['email'] = $email;
	
	$mail = new \PHPMailer\PHPMailer\PHPMailer();
	//$mail->isSMTP();
	$mail->Host = "smtp.gmail.com";
	$mail->SMTPAuth = true;
	$mail->Username = "Kumaraa.well@gmail.com"; //paste one generated by Mailtrap
	$mail->Password = "Vel@2020@Bha#"; //paste one generated by Mailtrap
	$mail->SMTPSecure = 'tls';
	$mail->Port = 587;

	$address = "kumaraa.well@gmail.com";
	$toadd= "khshameed1190@gmail.com";
	$bhn="BHN";
	$mail->setFrom($address, 'BHN Contact Form Submission');
	$mail->addAddress($toadd, $bhn);
	$mail->isHTML(true);

	$mail->Subject = "BHN Contact Form Submission";
	$mail->Body = $bodyContent;

	if(!$mail->send()){
	echo "Message could not be sent.";
	echo json_encode(array('flag'=>'mailer-error',"message"=>'Try Again Later'));
	}else{
	echo json_encode(array('flag'=>'success',"message"=>'Mail sent successfully'));
	exit;
	}
}
	
?>